### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by YOU-k** [jessica1338/CSHMM-TF-for-time-series-scRNA-Seq#2]
Hi there,
[data_matrix (1).txt](https://github.com/jessica1338/CSHMM-TF-for-time-series-scRNA-Seq/files/8038985/data_matrix.1.txt)

I managed to install the software and run the example successfully.
However, with my own data, I kept getting the error that 
`reading cells...
cell:1
Traceback (most recent call last):
  File "scdiff_init.py", line 105, in <module>
    run_scdiff_init(data_file,tfdna,config=config_file,large=large,dsync=dsync,output_file=args.output_file) #if it takes too long, set large="True" for large dataset
  File "scdiff_init.py", line 38, in run_scdiff_init
    ti=float(line[1])
IndexError: list index out of range`

I uploaded the data_matrix I have, which I think is in the format based on the instruction.
Could you please help me have a look and give me some suggestions about how to solve this?
Thanks!
Yue

**Comment by YOU-k** [comment]
Hi, I restricted the digits of the number to be at most 3, but it returns this error to me as well.

**Comment by YOU-k** [comment]
It works if I reset the cell labels. Thanks!
